import { useCanvasStore } from '@/stores/canvas-store'
import { useTimelineStore } from '@/stores/timeline-store'
import { useMappingStore } from '@/stores/mapping-store'
import type { AutoMapResult, CanvasToTimelineLink } from '@/types/mapping'
import type { ScriptNodeData } from '@/types/canvas'

export function runAutoMapper(): AutoMapResult {
  const canvasStore = useCanvasStore.getState()
  const timelineStore = useTimelineStore.getState()
  const mappingStore = useMappingStore.getState()

  // Clear existing auto-generated links
  const manualLinks = mappingStore.links.filter((l) => !l.autoGenerated)
  mappingStore.setLinks(manualLinks)

  const links: CanvasToTimelineLink[] = []
  const mappedNodeIds = new Set<string>()

  // Include existing manual links
  for (const link of manualLinks) {
    mappedNodeIds.add(link.canvasNodeId)
  }

  // Map canvas nodes to shots based on beat numbers and labels
  for (const shot of timelineStore.shots) {
    const beatMatch = shot.label.match(/\d+/)
    const shotBeat = beatMatch ? parseInt(beatMatch[0]) : null

    for (const node of canvasStore.nodes) {
      if (mappedNodeIds.has(node.id)) continue
      if (shot.linkedNodeIds.includes(node.id)) continue

      let matched = false
      const data = node.data as Record<string, unknown>

      // Match by beat number
      if (shotBeat && 'beatNumber' in data && data.beatNumber === shotBeat) {
        matched = true
      }

      // Match by label similarity
      if (!matched && 'label' in data) {
        const nodeLabel = String(data.label).toLowerCase()
        if (shot.label.toLowerCase().includes(nodeLabel) || nodeLabel.includes(shot.label.toLowerCase())) {
          matched = true
        }
      }

      if (matched) {
        // Link both in the mapping store and in the shot's linkedNodeIds
        const linkId = mappingStore.addLink(node.id, shot.id, 0.8, true)
        timelineStore.linkNodeToShot(shot.id, node.id)
        links.push({
          id: linkId,
          canvasNodeId: node.id,
          timelineItemId: shot.id,
          confidence: 0.8,
          autoGenerated: true,
        })
        mappedNodeIds.add(node.id)
      }
    }
  }

  const unmappedNodes = canvasStore.nodes
    .filter((n) => !mappedNodeIds.has(n.id))
    .map((n) => n.id)

  const unmappedItems = timelineStore.shots
    .filter((s) => s.linkedNodeIds.length === 0)
    .map((s) => s.id)

  return { links, unmappedNodes, unmappedItems }
}
