/**
 * One-shot migration that scans `canvas-item-store` for items whose
 * `content` is a `data:image/...;base64,...` URL, uploads each to
 * `/uploads/save`, and replaces the content with the returned
 * `/uploads/<uuid>.png` path.
 *
 * Why this exists: every image generated by an in-browser provider
 * (TokenRouter, Doubao image, paste-from-clipboard) lands as a data:
 * URL on the canvas-item store. Those data URLs are persisted directly
 * to IDB, accumulating to tens of megabytes per session. Then the
 * server-side session backup tries to POST that — gzip barely helps
 * (base64 already has low entropy), nginx 413s or upload bandwidth
 * gets saturated.
 *
 * Idempotent + safe:
 *   - Already-uploaded items (content starts with `/uploads/` or `http`)
 *     are skipped instantly.
 *   - Each upload is awaited individually so a single failure doesn't
 *     break the rest.
 *   - On any error, the item is left as-is so a retry on next load can
 *     pick it up.
 *
 * Runs on app startup via App.tsx useEffect.
 */

import { useCanvasItemStore } from '@/stores/canvas-item-store'

interface UploadResponse { url?: string; error?: string }

function isDataUrl(s: string | undefined | null): s is string {
  return typeof s === 'string' && s.startsWith('data:')
}

async function uploadDataUrl(dataUrl: string, filename: string): Promise<string> {
  const res = await fetch('/uploads/save', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ dataUrl, filename }),
  })
  if (!res.ok) throw new Error(`/uploads/save HTTP ${res.status}`)
  const json = (await res.json()) as UploadResponse
  if (!json.url) throw new Error(json.error ?? 'no url returned')
  return json.url
}

/**
 * Walk every canvas-item, migrate inline data: URLs, return a brief
 * summary so the caller can toast / log. Failures are counted but do
 * not throw — the user keeps using the app and we'll retry next load.
 */
export async function migrateInlineDataUrlsOnce(): Promise<{
  scanned: number
  migrated: number
  failed: number
  bytesFreed: number
}> {
  const store = useCanvasItemStore.getState()
  const items = store.items

  const candidates = Object.values(items).filter((it) => isDataUrl(it.content))
  if (candidates.length === 0) {
    return { scanned: Object.keys(items).length, migrated: 0, failed: 0, bytesFreed: 0 }
  }

  let migrated = 0
  let failed = 0
  let bytesFreed = 0

  // Bounded concurrency so we don't fire 50 simultaneous POSTs.
  const PARALLEL = 4
  const queue = [...candidates]
  async function worker() {
    while (queue.length > 0) {
      const item = queue.shift()
      if (!item || !isDataUrl(item.content)) continue
      const originalBytes = item.content.length
      try {
        const url = await uploadDataUrl(item.content, item.name || 'asset')
        useCanvasItemStore.getState().updateItem(item.id, { content: url })
        migrated++
        bytesFreed += originalBytes - url.length
      } catch (e) {
        failed++
        // eslint-disable-next-line no-console
        console.warn(`[data-url-migration] item ${item.id} (${item.name}) failed:`, (e as Error).message)
      }
    }
  }
  await Promise.all(Array.from({ length: PARALLEL }, () => worker()))

  return {
    scanned: Object.keys(items).length,
    migrated,
    failed,
    bytesFreed,
  }
}
