import type { CriterionKey } from './judge-schema'
import allowlistData from '../../../evolution/allowlist.json'

/**
 * Evolution loop configuration (HarnessX/AEGIS).
 *
 * IMPORTANT: this file — like gates.ts, judge-schema.ts and the judge prompt
 * (server/judge-prompts/six-criteria.md) — is part of the frozen verifier
 * surface and is deliberately NOT in EVOLVER_ALLOWLIST. The loop can never
 * edit its own reward function.
 */

export const EVOLUTION_CONFIG = {
  /**
   * Judge-noise tolerance: a candidate may score up to epsilon BELOW the
   * per-case baseline overall without counting as a regression. Calibrated
   * by running the bench twice on an unchanged harness (delta must be ≤ ε;
   * see bench.e2e verification).
   */
  epsilon: 0.25,
  /** No single criterion may drop more than this vs the baseline. */
  maxCriterionDrop: 1.0,
  /** Candidates generated by the Evolver per iteration. */
  candidatesPerIteration: 3,
  /** L3 (real Seedance video) evaluation cadence: every N shipped iterations. */
  l3EveryNShips: 5,
  criteriaWeights: {
    composition_art_style: 1,
    character_appeal: 1,
    continuity_consistency: 1,
    pacing_for_traffic: 1,
    shot_language: 1,
    expression_emotion: 1,
  } satisfies Record<CriterionKey, number>,
  /** Dedicated port for the unattended evolution dev server (worktree). */
  evolutionServerPort: 8090,
} as const

/**
 * Files the Evolver may patch (typed harness edits, HarnessX D2/D3).
 * Everything else — judge prompts, gates, registry, plugins, the evolution
 * scripts themselves — is hard-excluded and statically enforced in
 * scripts/evolution/lib/candidates.mjs before the Critic ever sees a
 * candidate. Source of truth is evolution/allowlist.json (shared with the
 * Node-side controller, which can't import this .ts file directly).
 */
export const EVOLVER_ALLOWLIST: RegExp[] = (allowlistData.patterns as string[]).map(
  (p) => new RegExp(p),
)

export function isAllowlisted(path: string): boolean {
  return EVOLVER_ALLOWLIST.some((re) => re.test(path))
}
