export interface CanvasToTimelineLink {
  id: string;
  assetId?: string;
  /** @deprecated use assetId */
  canvasNodeId: string;
  timelineItemId: string;
  confidence: number;
  autoGenerated: boolean;
}

export interface AutoMapResult {
  links: CanvasToTimelineLink[];
  unmappedNodes: string[];
  unmappedItems: string[];
}
