import { create } from 'zustand';
import { immer } from 'zustand/middleware/immer';
import { persist } from 'zustand/middleware';
import { v4 as uuid } from 'uuid';
import type { CanvasToTimelineLink } from '@/types/mapping';

interface MappingState {
  links: CanvasToTimelineLink[];
}

interface MappingActions {
  addLink: (canvasNodeId: string, timelineItemId: string, confidence?: number, autoGenerated?: boolean) => string;
  addLinkByAsset: (assetId: string, timelineItemId: string, confidence?: number, autoGenerated?: boolean) => string;
  addLinkToShot: (nodeId: string, shotId: string) => string;
  removeLink: (linkId: string) => void;
  removeLinkByNodeId: (canvasNodeId: string) => void;
  removeLinkByAssetId: (assetId: string) => void;
  removeLinkByItemId: (timelineItemId: string) => void;
  removeLinkFromShot: (nodeId: string, shotId: string) => void;
  getLinksForNode: (canvasNodeId: string) => CanvasToTimelineLink[];
  getLinksForAsset: (assetId: string) => CanvasToTimelineLink[];
  getLinksForItem: (timelineItemId: string) => CanvasToTimelineLink[];
  getLinksForShot: (shotId: string) => CanvasToTimelineLink[];
  setLinks: (links: CanvasToTimelineLink[]) => void;
  clearLinks: () => void;
}

export const useMappingStore = create<MappingState & MappingActions>()(
  persist(
  immer((set, get) => ({
    links: [],

    addLink: (canvasNodeId, timelineItemId, confidence = 1, autoGenerated = false) => {
      const id = uuid();
      set((state) => {
        state.links.push({ id, canvasNodeId, timelineItemId, confidence, autoGenerated });
      });
      return id;
    },

    addLinkByAsset: (assetId, timelineItemId, confidence = 1, autoGenerated = false) => {
      const existing = get().links.find(
        (l) => l.assetId === assetId && l.timelineItemId === timelineItemId
      );
      if (existing) return existing.id;
      const id = uuid();
      set((state) => {
        state.links.push({ id, assetId, canvasNodeId: assetId, timelineItemId, confidence, autoGenerated });
      });
      return id;
    },

    addLinkToShot: (nodeId, shotId) => {
      // Check for duplicate
      const existing = get().links.find(
        (l) => l.canvasNodeId === nodeId && l.timelineItemId === shotId
      );
      if (existing) return existing.id;

      const id = uuid();
      set((state) => {
        state.links.push({ id, canvasNodeId: nodeId, timelineItemId: shotId, confidence: 1, autoGenerated: false });
      });
      return id;
    },

    removeLink: (linkId) => {
      set((state) => { state.links = state.links.filter((l) => l.id !== linkId); });
    },

    removeLinkByNodeId: (canvasNodeId) => {
      set((state) => { state.links = state.links.filter((l) => l.canvasNodeId !== canvasNodeId); });
    },

    removeLinkByAssetId: (assetId) => {
      set((state) => { state.links = state.links.filter((l) => l.assetId !== assetId); });
    },

    removeLinkByItemId: (timelineItemId) => {
      set((state) => { state.links = state.links.filter((l) => l.timelineItemId !== timelineItemId); });
    },

    removeLinkFromShot: (nodeId, shotId) => {
      set((state) => {
        state.links = state.links.filter(
          (l) => !(l.canvasNodeId === nodeId && l.timelineItemId === shotId)
        );
      });
    },

    getLinksForNode: (canvasNodeId) => get().links.filter((l) => l.canvasNodeId === canvasNodeId),
    getLinksForAsset: (assetId) => get().links.filter((l) => l.assetId === assetId),
    getLinksForItem: (timelineItemId) => get().links.filter((l) => l.timelineItemId === timelineItemId),
    getLinksForShot: (shotId) => get().links.filter((l) => l.timelineItemId === shotId),
    setLinks: (links) => set({ links }),
    clearLinks: () => set({ links: [] }),
  })),
  { name: 'mapping-store' }
  )
);
